### ISSUE TITLE
[CI] Support macos on ARM64

### ISSUE THREAD

**Issue by Kyurenpoto** [Kyurenpoto-org/pbdt#118]
# Motivation

![Image](https://github.com/user-attachments/assets/61e0c1f6-de0d-4902-a9be-eb89ea09c671)

- In a GitHub Actions script, code that uses `std::print` fails to compile when setting `run-on: macos-latest`.
  - On `macos 14, xcode 15.4, apple clang 19, c++23`

# Run on `macos 15, clang 20`

https://github.blog/changelog/2025-04-10-github-actions-macos-15-and-windows-2025-images-are-now-generally-available/

from:
```
  macos-build:
    runs-on: macos-latest
    strategy:
      matrix:
        preset: [macos-debug, macos-release]
    continue-on-error: true

    steps
      # ...
      - name: install clang
        run: |
          brew install llvm@19
          echo PATH="/opt/homebrew/opt/llvm@19/bin:$PATH" >> $GITHUB_ENV
          brew link --overwrite llvm@19
      # ...
```
to:
```
  macos-build:
    runs-on: macos-15
    strategy:
      matrix:
        preset: [macos-debug, macos-release]
    continue-on-error: true

    steps
      # ...
      - name: install clang
        run: |
          brew install llvm@20
          echo PATH="/opt/homebrew/opt/llvm@20/bin:$PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/opt/llvm@20/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/llvm@20/include" >> $GITHUB_ENV
          brew link --overwrite llvm@20
      # ...
```

# Cache variables for `libc++`

from:
```
    {
      "name": "macos-base",
      "hidden": true,
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/out/build/${presetName}",
      "installDir": "${sourceDir}/out/install/${presetName}",
      "cacheVariables": {
        "CMAKE_C_COMPILER": "clang",
        "CMAKE_CXX_COMPILER": "clang++"
      },
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Darwin"
      },
      "vendor": {
        "microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
          "sourceDir": "$env{HOME}/.vs/$ms{projectDirName}"
        }
      }
    },
```
to:
```
    {
      "name": "macos-base",
      "hidden": true,
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/out/build/${presetName}",
      "installDir": "${sourceDir}/out/install/${presetName}",
      "cacheVariables": {
        "CMAKE_C_COMPILER": "clang",
        "CMAKE_CXX_COMPILER": "clang++",
        "CMAKE_CXX_FLAGS": "env{CPPFLAGS}",
        "CMAKE_EXE_LINKER_FLAGS": "$env{LDFLAGS}"
      },
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Darwin"
      },
      "vendor": {
        "microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
          "sourceDir": "$env{HOME}/.vs/$ms{projectDirName}"
        }
      }
    },
```
