### ISSUE TITLE
[CI] Support non-release

### ISSUE THREAD

**Issue by Kyurenpoto** [Kyurenpoto-org/pbdt#127]
# Motivation

![Image](https://github.com/user-attachments/assets/eeb67a14-b046-4b40-8cdc-f0fb14570f92)

There is no staging-test for non-release branches.

# Fix job condition

## `dev-stage-test-result.yml`

from:
```
      if: >
      github.event.workflow_run.head_branch == 'dev' || 
      startsWith(github.event.workflow_run.head_branch, 'release/') && 
      github.event.workflow_run.head_ref == ''
```
to:
```
      if: >
      github.event.workflow_run.head_branch == 'dev' || 
      startsWith(github.event.workflow_run.head_branch, 'release/') || 
      startsWith(github.event.workflow_run.head_branch, 'non-release/') && 
      github.event.workflow_run.head_ref == ''
```

## `ci.yml`

from:
```
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*
```
to:
```
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - release/*
      - non-release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - non-release/*
```
